[blacklist]
hotkeys = [
    "5F1AvW1YMA3wycLPDfvC6FgEeu4cXaicZ3nxsu51WQsu7ZzY",
    "5CkrU6o7eDNbf3SJdyzZu4fK96eHr4KFhjUjFRtbsgZHEXAC",
    "5G7AawrGnYhPgS8nHC9W93MsWan3R3i8VJ3qHaetMBDRf9zx",
    "5GTRujZS7JoCHEYapRD32o2iK26z9nsM7u1ZEmnc1BmGQTLb",
    "5EAJxoyP1QrUkCyyDf5zx89uVtuZ2cxJjoA1eixN1gwT4xvT",
    "5F28AhQcDSoMPrnoAgQc1TmvBTBS5HPXLovuA3dgXqJK9kRn",
    "5CdTAxpZcnCJP5MZ7qNncgbFSddbyKf9dyzM5WSbkXYkDmAQ",
    "5ERxpTnQBHQSFSHxQfBwncyg2nX6fwd9zuAgWEc9zhKSS3o4",
    "5ENnzZUHbMqjeZw4nMffCfaRBVRX3wPcN4qNd9g1dSzdQ3AS",
    "5CVD4y13Lo1k9mN46d39i8StB5ecMz4sA3YqMaHjUKg5MNE1",
    "5EHd7FxG2sPqTNbmEjDU9SiMkPGdbiPNw2PXgf6QBPjG3Sge",
    "5CMk8v2x8DSeKhggxTTwdXpiTDaogFdFh34vrvawgCn62Ri3",
    "5E9t5M8YaetNoXbwdb16zUfhrtJGLTjqUZLSxtSAjBquMYk8",
    "5EFPzb95KBbKZWFraUqLgf93uatCKz11eGKfF1mHN6zN5hix",
    "5HgBkh5nYPvJwfWwyZdPTZepx1Ta3s7VvqqyK4ycmB38MASW",
    "5CP6EzFLcWZZ5CCZGCi96EhbgxMTQ3Ragq1ziGyXXjMEywpX",
    "5DfeE7AzhPtcSQ7HfkLuBb3o3EHRsHwMkirkW1DHeS2576zD",
    "5EUwLvCGQGWVBzuKCmVig3z2WnPScmToPvXPd4AJKBKJ9oAB",
    "5CfjjV4xaxJ1Bg82ysU9TFEwu4Bt85skz3MKhAdUyKKmqoNp",
    "5Gbj4KaQPgDMdVgaaMXrzNqSYQPBXz7mCT7XfESLyLW7F3pP",
    "5DHXoVMi6VWigqdeCwGuxUKPJuCcJrRdTnbN85T4vgEdTcn9",
    "5GgX9NvYVcp1to4kyUDXyxyc8zEVBK51s4m8geEjfrzpmbzt",
    "5FcPNdTGmVMAmimvkUkFACfZQprhrPSzcwx1sQNUCfDghxe2",
    "5F1K7TEV5a7bK2bt7zT3K7wLPWrq4QcBeq9ooTWWWLuVyWbo",
    "5Ev5oSnyb2QazBzXG5WdzonB6v2wKMLM6DTps7sLRuHC84Mp"
]