[blacklist]
hotkeys = [
    "5F1AvW1YMA3wycLPDfvC6FgEeu4cXaicZ3nxsu51WQsu7ZzY",
    "5CkrU6o7eDNbf3SJdyzZu4fK96eHr4KFhjUjFRtbsgZHEXAC",
    "5G7AawrGnYhPgS8nHC9W93MsWan3R3i8VJ3qHaetMBDRf9zx",
    "5GTRujZS7JoCHEYapRD32o2iK26z9nsM7u1ZEmnc1BmGQTLb",
    "5EAJxoyP1QrUkCyyDf5zx89uVtuZ2cxJjoA1eixN1gwT4xvT",
    "5F28AhQcDSoMPrnoAgQc1TmvBTBS5HPXLovuA3dgXqJK9kRn",
    "5CdTAxpZcnCJP5MZ7qNncgbFSddbyKf9dyzM5WSbkXYkDmAQ",
    "5ERxpTnQBHQSFSHxQfBwncyg2nX6fwd9zuAgWEc9zhKSS3o4",
    "5ENnzZUHbMqjeZw4nMffCfaRBVRX3wPcN4qNd9g1dSzdQ3AS"
]