name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync --extra all

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v1
        with:
          args: check

      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v1
        with:
          args: format --check

      - name: Run Tests
        run: uv run --frozen pytest