name: Ruff Format and Lint Checker

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v1
        with:
          args: check
      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v1
        with:
          args: format --check